plugins:
  # Used for warming up JVM container.
  - serverless-plugin-warmup

custom:
  params:
    product: "demo-api-server"
  warmup:
    timeout: 20
    events:
      # Run every 5 minutes from 00:00 to 14:00 UTC, Monday to Friday.
      - schedule: "cron(0/5 0-14 ? * MON-FRI *)"
    concurrency: 2
    prewarm: true

service: ${self:custom.params.product}

provider:
  name: aws
  runtime: java8
  timeout: 60
  memorySize: 128

functions:
  hello:
    handler: com.sheepduke.api.server.hello.HelloHandler::handleRequest
    package:
      artifact: build/libs/demo-api-server-1.0.jar
    events:
      - http:
          path: ${self:custom.params.product}/hello
          method: post
    warmup:
      enabled: true
